### ISSUE TITLE
#1393 Dark Mode Theme

### ISSUE THREAD

**Issue by xmikedanielsx** [LibreHardwareMonitor/LibreHardwareMonitor#1396] opened 2024-07-30 14:08 UTC
Request Person: JayzTwoCents
Request From: https://www.youtube.com/watch?v=sX2ThUWNXio
Request:
As an end User using high contrast screens or not, it seems imperative in any current application to be able to utilize a dark mode. As new screens and evolving technologies in them seem to have a higher contrast ratio and brightness levels and this tends to hurt the eyes. Also, there are many other benefits from having dark mode.

Acceptance Criteria:
The application itself will need to be changed to allow for the back and forecolors to be altered depending on in dark mode or not. An easy switcher would need to be implemented. An example Mock Up of the switcher has been made.
![image](https://github.com/user-attachments/assets/ff12a73b-c054-448f-8d3a-141f6d414d4d)

**Comment by pedrosimoes79** [comment] 2024-07-30 18:11
there is anyone already doing this one?

**Comment by xmikedanielsx** [comment] 2024-07-30 19:28
I took a quick stab at it. but please please do it! .

**Comment by Tellinq** [comment] 2024-07-31 00:41
I hate to be _that_ guy…. FYI, this is a duplicate of #116 and PR #847 

I recommend closing this issue in favor of the PR/older issue.

**Comment by PhyxionNL** [comment] 2024-07-31 08:13
Yes, closing due to dupe of #116.

**Closed by PhyxionNL** 2024-07-31 08:13 UTC
