### ISSUE TITLE
NaN and Infinity CPU clock speeds reported, in addition to incorrect CPU voltages

### ISSUE THREAD

**Issue by schiffy91** [LibreHardwareMonitor/LibreHardwareMonitor#801] opened 2022-08-21 19:49 UTC
LibreHardwareMonitor is reporting NaN and infinity as my CPU's clock speeds after enabling Core Isolation's Memory Integrity feature in Windows 11. Also, the CPU voltages are now incorrect -- it's frequently reporting the CPU voltage is at 1.55V. Confirmed with Ryzen Master, my BIOS, and HWInfo that my CPU is in fact operating at around 3-4GHz and my CPU voltage significantly lower. 

When I disable Core Isolation's Memory Integrity feature, everything is reported normally again.

Attaching a report
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/9389853/LibreHardwareMonitor.Report.txt)
.

**Comment by PhyxionNL** [comment] 2022-08-24 12:47
Thanks, this is a duplicate of https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/566, closing.

**Closed by PhyxionNL** 2022-08-24 12:47 UTC
