### ISSUE TITLE
Memory temperature not showing

### ISSUE THREAD

**Issue by ThomAce** [LibreHardwareMonitor/LibreHardwareMonitor#1088] opened 2023-06-02 10:14 UTC
Memory temperature could not be monitored through LibreHardwareMonitor. Software like Aida64 can read these sensor data, but I did not found any possibility to get it from this one. Any options, workaround, solution?

**Comment by PhyxionNL** [comment] 2023-06-02 13:07
Duplicate of #395.

**Closed by PhyxionNL** 2023-06-02 13:07 UTC
