### ISSUE TITLE
Nothing displayed for AMD RX 5700 XT GPU 

### ISSUE THREAD

**Issue by binary100100** [LibreHardwareMonitor/LibreHardwareMonitor#134] opened 2019-09-23 21:25 UTC
It only shows the card but no details.
Latest Windows 10, latest drivers.
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/3644229/LibreHardwareMonitor.Report.txt)

**Comment by fboldog** [comment] 2019-10-09 09:00
Hi,

could you try this version? 
https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts
It's use some newer ATI api call.

Is there any information displayed about your card?

**Comment by KyodaiKen** [comment] 2019-10-12 15:21
I know someone with this exact GPU (AiB partner version, not reference), I asked him if he can help us troubleshooting. According to him, he has seen data from this card once and it was gone later with the same LHM version. I will keep y'all updated.

**Comment by binary100100** [comment] 2019-10-20 16:05
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/3748036/LibreHardwareMonitor.Report.txt)

**Comment by dONKdONKdONKdONK** [comment] 2019-10-22 08:15
[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/3754347/LibreHardwareMonitor.Report.txt)

**Comment by TrickyDee42** [comment] 2019-10-28 08:04
Any news on this?

**Comment by fboldog** [comment] 2019-10-31 16:34
Hi, could you run my small tester app? @dONKdONKdONKdONK , @TrickyDee42 , @binary100100 
https://github.com/fboldog/adl-tester/suites/290283753/artifacts/219541
And post the output to this issue?

It runs from command line, without any admin rights and actually opens the first adapter. 
For example: my Vega56 produces this output:
![adl-tester](https://user-images.githubusercontent.com/422679/67966571-65d46d80-fc04-11e9-9ddc-ea9fb3f3ab28.png)


Of course you can check the source code:
https://github.com/fboldog/adl-tester

**Comment by dONKdONKdONKdONK** [comment] 2019-11-01 10:15
![image](https://user-images.githubusercontent.com/56356781/68018095-2c494400-fc90-11e9-8673-8a82ad622dd8.png)

**Comment by fboldog** [comment] 2019-11-01 12:29
@dONKdONKdONKdONK thanks.
Thanks, just as I excepted. :(
The 5700 (XT) cards using the new v8 aka. OverdriveN api. 
I will create a new test app for this in the coming days.

**Comment by fboldog** [comment] 2019-11-01 13:31
@dONKdONKdONKdONK one more question.
does your your 5700xt is supported by GPU-Z and does sensors tab are filled with data?

**Comment by dONKdONKdONKdONK** [comment] 2019-11-01 13:37
![image](https://user-images.githubusercontent.com/56356781/68028403-b6070a80-fcac-11e9-9629-62622438b7c8.png)

**Comment by TrickyDee42** [comment] 2019-11-19 08:15
Any news?

**Comment by cednieb** [comment] 2019-12-02 18:51
fboldog , some progress ?

**Comment by fboldog** [comment] 2019-12-03 18:48
Hey guys, so, actually not really.
AMD isn't update their framework (AMD Display Library aka. ADL) since months. Which is not really supports NAVI GPUs. I tired many ways, without any real progress. :(
Actually I using a Vega56 card, debugging without a 5700 (XT) is hard or nearly impossible. :D

**Comment by cednieb** [comment] 2019-12-03 19:23
It seems that works \display-library-master\Sample\Overdrive8 at less for the hotspot

-----------------------------------------
Adapter Index[0]
 -----------------------------------------
itemID:OD8_OPERATING_TEMP_MAX: is not Visible
OD8_OPERATING_TEMP_MAX:maxValue:110
minValue:50
defaultValue:110
-----------------------------------------
itemID:OD8_FAN_TARGET_TEMP: is not Visible
OD8_FAN_TARGET_TEMP:maxValue:100
minValue:25
defaultValue:75
-----------------------------------------
itemID:OD8_POWER_PERCENTAGE: is Visible
actualValue:0
OD8_POWER_PERCENTAGE:maxValue:20
minValue:-50
defaultValue:0
-----------------------------------------
ADLSensorType: PMLOG_TEMPERATURE_EDGE - Current Temp
PMLOG_TEMPERATURE_EDGE.supported:1
PMLOG_TEMPERATURE_EDGE.value:35
ADLSensorType: PMLOG_TEMPERATURE_HOTSPOT - Junction Temp
PMLOG_TEMPERATURE_HOTSPOT.supported:1
PMLOG_TEMPERATURE_HOTSPOT.value:35
-----------------------------------------

**Comment by cednieb** [comment] 2019-12-03 20:13
Thats works
[https://pastebin.com/99QmJ5TU](url)

**Comment by fboldog** [comment] 2019-12-03 21:03
Hm, i look after it. Thanks for this information.

**Comment by cednieb** [comment] 2019-12-03 21:14
I try to fix your adltester .
Can you help ?

**Comment by fboldog** [comment] 2019-12-04 22:41
I pushed an initial version of this query.
https://github.com/fboldog/adl-tester/suites/342680815/artifacts/552948
Please someone with 5700 (or XT) test the output.

**Comment by cednieb** [comment] 2019-12-04 22:47
https://pastebin.com/hyFukRiv
Source code please

**Comment by fboldog** [comment] 2019-12-04 22:50
Thanks, looks good. Going forward (tomorrow) with checking settings which is enabled, etc.

**Comment by fboldog** [comment] 2019-12-05 20:02
Please someone test again, but now in my LHWM build. :)
https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts
Thanks!

**Comment by cednieb** [comment] 2019-12-05 20:19
Source code plz , I can compile it .

**Comment by fboldog** [comment] 2019-12-05 20:22
https://github.com/fboldog/LibreHardwareMonitor/tree/support-rx5700-series-issue-134

**Comment by cednieb** [comment] 2019-12-05 20:28
That works , I retrieve the same values ( Aida , hwinfo )

**Comment by cednieb** [comment] 2019-12-05 20:28
Thanks for your work

**Comment by fboldog** [comment] 2019-12-05 20:37
Could you make a screenshot?
You're welcome. :)

**Comment by cednieb** [comment] 2019-12-05 20:53
http://thisiteisnot.online/ScreenShot001.jpg

**Comment by dONKdONKdONKdONK** [comment] 2019-12-05 21:20
![image](https://user-images.githubusercontent.com/56356781/70274708-86b05580-17a4-11ea-9eb3-9a0ee5c93354.png)

Running Heaven - GPU Core Clock not reporting correctly.  Everything else just works!
Thanks so much

**Comment by fboldog** [comment] 2019-12-06 11:06
@dONKdONKdONKdONK & @cednieb 
could test the new version (https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts - 1.0.21)? 
- fixed voltage display
- added some new values

if it works, this version will be the PR.

**Comment by dONKdONKdONKdONK** [comment] 2019-12-06 12:19
![image](https://user-images.githubusercontent.com/56356781/70322500-2829bc80-1822-11ea-8713-d5ff18481fa1.png)

Shows correct Max Value on core but no SOC value

**Comment by cednieb** [comment] 2019-12-06 13:43
![Screenshot](http://thisiteisnot.online/01.png)
http://thisiteisnot.online/ScreenShot002.jpg

**Comment by inks007** [comment] 2019-12-07 14:13
@fboldog awesome work, thanks.

![image](https://user-images.githubusercontent.com/12200916/70375912-7e8c1d80-193e-11ea-926e-e0d524dab1c4.png)


GPU fan shows 65535 RPM / 1323.0% instead of 0 RPM / 0% (it is unplugged).

**Comment by fboldog** [comment] 2019-12-07 18:32
@inks007 disconnected fan fixed
@dONKdONKdONKdONK soc value assigned to bad sensor :) this is fixed too.

Please check the new build at https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts (1.0.22)

**Comment by dONKdONKdONKdONK** [comment] 2019-12-08 15:11
That works, thanks again. Now I can keep an eye on my dodgy 5700 xt

**Comment by inks007** [comment] 2019-12-08 15:38
I see that the fan entry is removed (because of the null value) if the sensor returns 65535. Perhaps returning N/A, zero or '-'  might be better. ADL might be reporting -1 for a dead fan, which would be relevant for others. I've modded my 5700XT, so I know that it shouldn't have a fan reading - I can just hide the entries.

My fan header is inaccessible - I can't double check if a connected fan that is stuck/stopped reads 0 RPM or 65535 RPM. Might be useful if @dONKdONKdONKdONK or @cednieb could check this,

**Comment by dONKdONKdONKdONK** [comment] 2019-12-08 16:06
65535 RPM is a driver issue I think. I had it on GPU-Z and Wattman when I first purchased the card. It was resolved by a v-BIOS update and new drivers, it came back with the latest Radeon driver 19.12.1 but a new v-BIOS sorted it out. My RPM now reads either 0 or 400-450 RPM when the fans are stopped.
See pic with GPU-Z, LHW and Wattman OSD
![image](https://user-images.githubusercontent.com/56356781/70392124-4f27f000-19d4-11ea-8777-9923232f90a6.png)

**Comment by fboldog** [comment] 2019-12-08 20:32
I changed to '-' version, when it's reported as disconnected.
65535 is not a bug, this is the ushort (or UInt16) max value, which is OK for reporting a disconnected fan. :)
New build on same place: https://ci.appveyor.com/project/fboldog/librehardwaremonitor/build/artifacts (1.0.23)

**Closed** 2019-12-17 08:47 UTC
