### ISSUE TITLE
Add support for ITE IT8792E/IT8795E fan controllers 

### ISSUE THREAD

**Issue by PrinceLikesCookies** [LibreHardwareMonitor/LibreHardwareMonitor#662] opened 2022-02-13 04:37 UTC
Motherboard: B550 Aorus Pro V2

- I have seen multiple people report problems with these chip sets while using Rem0's fan control. The main problems are because the fan headers, sysfanpump5 or sysfanpump6, sysfan 4, do not work because the chipset ITE IT8792E/IT8795E are not compatible with fancontrol. 

- #251 #235 had similar issues. https://github.com/Rem0o/FanControl.Releases/issues/69

- I have almost to no clue about coding but I do want to try and help the community as much as possible since it appears this issue has been appearing since 2020.

**Comment by PhyxionNL** [comment] 2022-02-22 21:59
Duplicate of already linked issues, closing.

**Closed by PhyxionNL** 2022-02-22 21:59 UTC
