### ISSUE TITLE
HDD temp through HBA/RAID card

### ISSUE THREAD

**Issue by jhhoffma3** [LibreHardwareMonitor/LibreHardwareMonitor#1073] opened 2023-05-08 21:27 UTC
LHM lacks the ability to pull temperature data from HDD's attached via SAS/HBA/RAID card.  This is common as the data is not readily available to most system reports.  However, HDSentinal is an example of software that is able to do this, but lacks the other great features of LHM.

Is it possible to look into how this is done in HDSentinal and implement a similar feature?

LHM screen:
![Screenshot 2023-05-08 172351](https://user-images.githubusercontent.com/62849993/236938944-ebeb5216-5ccd-44fb-9533-9ee3427a8504.png)

HDSentinal screen:
![Screenshot 2023-05-08 172838](https://user-images.githubusercontent.com/62849993/236939313-973922d0-0cb0-4051-a123-13e2455622ed.png)

**Comment by zotabee** [comment] 2023-06-04 13:24
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/375

**Comment by PhyxionNL** [comment] 2023-06-15 14:41
Duplicate of #375.

**Closed by PhyxionNL** 2023-06-15 14:41 UTC
