### ISSUE TITLE
Laptop CPU (AMD Ryzen * 7***U) weird values for clock speed (and Voltages)  ( Duplicate to #566 )

### ISSUE THREAD

**Issue by Eno77** [LibreHardwareMonitor/LibreHardwareMonitor#1310] opened 2024-04-10 09:10 UTC
Since the similar 5**** Series seem to work it may be an easy fix?

![grafik](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/33687620/6d9b23ad-0002-40bb-aed1-4c1b615a0ac9)

maybe due to wrong factor recognition?

![grafik](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/33687620/b699261f-9adc-493f-82e8-b282dccc35d7)

And here the voltages (maybe correct, but negative values seem weird:

![grafik](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/33687620/7f9db495-2eeb-4672-a248-87b263254a2c)

Version:

the latest nightly
![grafik](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/33687620/1f55f298-5bef-46cb-a2f7-c94f48a6b256)

**Comment by Eno77** [comment] 2024-04-10 09:19
I dont know, if its related, but voltages for integrated graphics are too high too: (maybe worth another issue?)

![grafik](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/assets/33687620/e840c6e0-c079-4b21-8fbd-5338ec2cdd25)

**Comment by ntoff** [comment] 2024-05-07 19:38
Possible duplicate of https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/566 Do you have core isolation turned on in windows device security settings?

**Comment by Eno77** [comment] 2024-05-08 09:10
hi @ntoff

thanks for pointing to this, you are right, unfortunately I can not deactivate the according setting since its set by the domain admin and probably should stay this way to meet security standards.

But I reproduced the issue on my private Desktop PC (5800X3D) -> turning on kernel isolation causes this, so its in fact a duplicate.

**Closed** 2024-05-08 09:33 UTC
