### ISSUE TITLE
No Memory temperature

### ISSUE THREAD

**Issue by Neros7** [LibreHardwareMonitor/LibreHardwareMonitor#989] opened 2023-02-28 14:32 UTC
I can't see a Temperature under the Generic Memory tab, but it is picked up by hwinfo, I am using the latest release and a MSI B550 Tomahawk motherboard on Windows with G.Skill Memory

**Comment by PhyxionNL** [comment] 2023-03-15 17:11
Duplicate of #395.

**Closed by PhyxionNL** 2023-03-15 17:11 UTC
