### ISSUE TITLE
i5-13500h The cpu cannot read the cpu frequency and temperature

### ISSUE THREAD

**Issue by lisonglin980** [LibreHardwareMonitor/LibreHardwareMonitor#1021] opened 2023-03-21 08:17 UTC
i5-13500h The cpu cannot read the cpu frequency and temperature

[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/11026177/LibreHardwareMonitor.Report.txt)

![image](https://user-images.githubusercontent.com/68982838/226550351-e59792a4-19d0-4fe7-8880-916543346f6b.png)
![image](https://user-images.githubusercontent.com/68982838/226550393-b9fb7b64-23d4-458b-834f-e503b2c769c5.png)
(https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/11026166/LibreHardwareMonitor.Report.txt)

**Comment by PhyxionNL** [comment] 2023-03-21 09:07
Duplicate of #1021.
Status: Installing driver "E:\下载\LibreHardwareMonitor-net472\LibreHardwareMonitor.sys" failed and file exists

**Closed by PhyxionNL** 2023-03-21 09:07 UTC

**Comment by MrLee980** [comment] 2023-03-21 09:47
The LibreHardwareMonitor.sys file does not exist in the E:\下载\librehardwareMonitor. net472 2\ directory
